<?php
declare(strict_types = 1);
require_once 'base.php';
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<?php
if (!empty($publicationBooks)) {
    echo '<div style="padding: 30px 10px 30px 60px; border-left: 2px solid black; margin-left: 30px">';
    foreach ($publicationBooks as $publicationBook) {
        $publicationBook->printInfo();
    }
    echo '</div>';
}
?>

</body>
</html>